name: Build EXE
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
      - name: 修复依赖问题
        run: |
          npm install
          npm uninstall node-sass
          npm install sass sass-loader@10 --save-dev
      - name: 构建前端
        run: npm run build
      - name: 安装 Electron
        run: npm install electron electron-builder --save-dev
      - name: 打包 EXE
        run: npm run electron:build
      - name: 上传 EXE
        uses: actions/upload-artifact@v4
        with:
          name: lucky-draw-exe
          path: electron-dist/
