name: Build EXE
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.npm
            ~/.electron
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Install dependencies
        run: |
          npm install
          npm uninstall node-sass
          npm install sass sass-loader@10 --save-dev

      - name: Install Electron
        run: npm install electron@28.0.0 electron-builder@24.6.3 --save-dev  # 关键修正点

      - name: Build project
        run: npm run build

      - name: Build EXE
        run: npm run electron:build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lucky-draw-exe
          path: electron-dist/
